sudo: required

language: c

services:
    - docker

os:
    - linux
    - osx

before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew update
        fi

install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew install docker
        fi

script:
    - export PATH="$PATH:$PWD"; cd .travis; ./test-readlink.sh; cd ..
    - ./dockerrun.sh hello-world
    - ./composer.sh --version
    - ./deployer.sh --version
    - ./docker-compose.sh --version
    - ./git.sh --version
    - ./lualatex.sh --version
    - ./pandoc.sh --version
    - ./pdftex.sh --version
    - ./xelatex.sh --version
